---
- hosts: all
  sudo: true
  roles:
    - role: aws-credentials
      aws_credentials_user: vagrant
      aws_credentials_group: vagrant
      aws_credentials_profile_destination: default
      aws_credentials_access_key: blah
      aws_credentials_secret_access_key: blah_bla

    #this will only work if aws credentials have been configured on the box that is running this
    - role: aws-credentials
      aws_credentials_user: vagrant
      aws_credentials_group: vagrant
      aws_credentials_access_key: ''
      aws_credentials_secret_access_key: ''
      aws_credentials_profile_destination: real
      aws_credentials_profile_source: default
